version: 2.1

orbs:
  architect: giantswarm/architect@0.9.0

workflows:
  test:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: app-service
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-app-service-to-quay
          image: "quay.io/giantswarm/app-service"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-app-service-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/app-service"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-app-service-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "app-service"
          requires:
            - push-app-service-to-quay
            - push-app-service-to-aliyun
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
